name: Docker Image CI multiplatform

on:
  release: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u syvita --password-stdin    
      - name: build the image
        run: docker buildx build --tag ghcr.io/syvita/bitcoin:latest --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: push to ghcr
        run: docker push ghcr.io/syvita/bitcoin:latest
